# permissions for end users to view gatlings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gatling-viewer-role
rules:
- apiGroups:
  - gatling-operator.tech.zozo.com
  resources:
  - gatlings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gatling-operator.tech.zozo.com
  resources:
  - gatlings/status
  verbs:
  - get
