name: Feature Request
description: Suggest an idea for gatling-operator
title: "[Feature Request]: "
labels: ["feature"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
    validations:
      required: true
