apiVersion: v1
data:
  # dummy base64ed slack incoming webhook url
  incoming-webhook-url: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvQUJDREVGR0hJL1hYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWA==
kind: Secret
metadata:
  name: gatling-notification-slack-secrets
type: Opaque
