apiVersion: gatling-operator.tech.zozo.com/v1alpha1
kind: Gatling
metadata:
  name: gatling-sample01
spec:
  generateReport: false                                   # The flag of generating gatling report
  notifyReport: false                                     # The flag of notifying gatling report
  cleanupAfterJobDone: true                               #  The flag of cleaning up gatling jobs resources after the job done
  podSpec:
    gatlingImage: GATLING_IMAGE                           # Optional. Default: denvazh/gatling:latest. The image that will be used for Gatling container.
    rcloneImage: rclone/rclone                            # Optional. Default: rclone/rclone:latest. The image that will be used for rclone conatiner.
    resources:                                            # Optional. Resources specifies the resource limits of the container.
      limits:
        cpu: "500m"
        memory: "500Mi"
    affinity:                                             # Optional. Affinity specification
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
    tolerations:
      - key: "node-type"
        operator: "Equal"
        value: "non-kube-system"
        effect: "NoSchedule"
  cloudStorageSpec:
    provider: "aws"                                       # Provider specifies the cloud provider that will be used. Supported providers: "aws"
    bucket: "gatling-operator-reports"                    # Bucket name in cloud storage service, on which Gatlilng report files are stored
    region: "ap-northeast-1"                              # Optional. Default: "ap-northeast-1" for aws provider. Region name
    #env:                                                 # Optional. Environment variables to be used for connecting to the cloud providers
    #  # For S3 see also the env variables for auth: https://rclone.org/s3/#authentication
    #  - name: AWS_ACCESS_KEY_ID
    #    value: xxxxxxxxxxxxxxx
    #  - name: AWS_SECRET_ACCESS_KEY
    #    value: xxxxxxxxxxxxxxx
  notificationServiceSpec:
    provider: "slack"                                     # Notification provider name. Supported provider: "slack"
    secretName: "gatling-notification-slack-secrets"      # The name of secret in which all key/value sets needed for the notification are stored
  testScenarioSpec:
    # startTime: 2021-09-10 08:45:31                      # Optional. Start time of running test scenario in UTC. Format: %Y-%m-%d %H:%M:%S
    parallelism: 3                                        # Optional. Default: 1. Number of pods running at any instant
    # simulationsDirectoryPath: "/dir-path-to-simulation" # Optional. Default: /opt/gatling/user-files/simulations
    # resourcesDirectoryPath: "dir-path-to-resources"     # Optional. Default: /opt/gatling/user-files/resources
    # resultsDirectoryPath: "dir-path-to-results"         # Optional. Default: /opt/gatling/results.
    simulationClass: "MyBasicSimulation"                  # Gatling simulation class name
    # simulationData:                                     # Optional. Default: empty string map. Simulation Scala data to be created as ConfigMap that is mounted on simulations dir
    # resourceData:                                       # Optional. Default: empty string map. Resource data used with Simulation scala to be created as ConfigMap that is mounted on resource dir
    # gatlingConf:                                        # Optional. Default: empty string map. Gatling Conf data to be created as ConfigMap that is mounted on gatling conf dir
    env:                                                  # Optional. Environment variables to be used in Gatling Simulation Scala
      - name: ENV
        value: "dev"
      - name: CONCURRENCY
        value: "1"
      - name: DURATION
        value: "1"
      - name: SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: gatling-basic-simulation-secrets
            key: SECRET_KEY
