name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - add-ci
      - main
    paths-ignore:
      #- '.github/workflows/**'
      - '**.md'
      - '.gitignore'    
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - run: go version

      - name: Get Go Paths
        id: go-paths
        run: |
          echo ::set-output name=mod_cache::$(go env GOMODCACHE)
          echo ::set-output name=build_cache::$(go env GOCACHE)

      - name: Go modules and build cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.go-paths.outputs.mod_cache }}
            ${{ steps.go-paths.outputs.build_cache }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Go modules sync
        run: go mod tidy

      - name: Run Tests
        run: make test

      - name: Verify manifests are up-to-date
        run: |
          make manifests
          git diff --exit-code
